apiVersion: v1
kind: Service
metadata:
  name: {{ include "zincobserve.fullname" . }}-compactor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "zincobserve.labels" . | nindent 4 }}
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zincobserve.selectorLabels" . | nindent 4 }}
    role: compactor
