apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zincobserve.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "zincobserve.labels" . | nindent 4 }}
type: Opaque
stringData:
  ZO_USER_NAME: "{{ .Values.auth.ZO_ROOT_USER_EMAIL }}"
  ZO_USER_PASSWORD: "{{ .Values.auth.ZO_ROOT_USER_PASSWORD }}"
