apiVersion: v1
entries:
  etcd:
  - annotations:
      category: Database
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 3.5.9
    created: "2024-02-02T10:52:42.681303+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: etcd is a distributed key-value store designed to securely store
      data across a cluster. etcd is widely used in production on account of its reliability,
      fault-tolerance and ease of use.
    digest: 4667e0cb387874c9c15206d9fe9d228167f397b2587b480a999241c1d9f3b598
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/etcd/img/etcd-stack-220x234.png
    keywords:
    - etcd
    - cluster
    - database
    - cache
    - key-value
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: etcd
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/etcd
    urls:
    - charts/etcd-8.11.4.tgz
    version: 8.11.4
  minio:
  - apiVersion: v1
    appVersion: RELEASE.2023-02-10T18-48-39Z
    created: "2024-02-02T10:52:42.682459+05:30"
    description: Multi-Cloud Object Storage
    digest: 3f935a310e1b5b873052629b66005c160356ca7b2bd394cb07b34dbaf9905e3f
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - charts/minio-5.0.7.tgz
    version: 5.0.7
generated: "2024-02-02T10:52:42.679276+05:30"
